MEMORY
{
  RAM : ORIGIN = 0x40000000, LENGTH = 2M
}

REGION_ALIAS("VECTORS", RAM);
REGION_ALIAS("CODE", RAM);
REGION_ALIAS("DATA", RAM);
REGION_ALIAS("STACKS", RAM);

_num_cores = 1;
_pack_stacks = 1;
