MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 1M
  SRAM  : ORIGIN = 0x40000000, LENGTH = 1M
}

REGION_ALIAS("VECTORS", FLASH);
REGION_ALIAS("CODE", FLASH);
REGION_ALIAS("DATA", SRAM);
REGION_ALIAS("STACKS", SRAM);

_num_cores = 1;
_pack_stacks = 1;
